baseURL: "https://hyper6.netlify.app/"
languageCode: "en-us"
title: "Hyperhidrosis-uk"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
